"""Every write this project makes to the GitHub API goes through send(), and nothing else.

PR-Lens promises it never opens a pull request, pushes, applies a suggestion or approves.
The App's permissions do not keep that promise. Contents read-only stops a push, but Pull
requests read and write, which posting a review comment needs, also permits opening a
pull request and approving one. So the promise is kept here: ALLOWED is an explicit list
of (method, path) routes, and a write matching none of them raises before it leaves the
process.

What enforces it, in tests/test_github_writes.py: the allowlist holds no route that opens
a pull request or approves one, and no module outside this one makes an HTTP call that
could write. The read client's own send is typed to GET alone.

Adding a route is a deliberate edit to ALLOWED with its reason, and to the test that
lists what ALLOWED holds.

Phase 4 added the one route that writes to someone else's repository: a single review
comment on one line, through pulls/{n}/comments. Not through pulls/{n}/reviews, which
accepts event=APPROVE in the same body as a comment and so stays forbidden. The comment
route carries a body check as well as a path, and the check is where two more promises are
kept: every comment ends with DISCLOSURE, and the body holds only the keys a single
right-side line comment needs. A comment that breaks either raises here, before it leaves
the process, whichever code path built it.
"""

import re
from collections.abc import Callable
from dataclasses import dataclass
from typing import Any
from urllib.parse import urlsplit

import httpx

API_HOST = "api.github.com"

WRITE_METHODS = frozenset({"POST", "PUT", "PATCH", "DELETE"})

# One path segment of an owner or repository name, as GitHub allows them.
_NAME = r"[A-Za-z0-9._-]+"


# Every comment says what wrote it. Kept short and plain: the point is that nobody mistakes
# it for a person, not an advertisement.
DISCLOSURE = (
    "<sub>AI-generated by [PR-Lens](https://github.com/SURYAPRASATHJP/pr-lens), "
    "an opt-in reviewer. It can be wrong: resolve or reply to dismiss.</sub>"
)

# A line comment is under a hundred words by instruction. Anything near GitHub's own
# 65,536 limit is a bug upstream, not a comment.
MAX_COMMENT_CHARS = 4000

_COMMENT_KEYS = frozenset({"body", "commit_id", "path", "line", "side"})


class ForbiddenWrite(RuntimeError):
    """A write that is not on the allowlist. A bug in the caller, never a network error."""


def disclosed(body: str) -> str:
    return f"{body.rstrip()}\n\n{DISCLOSURE}"


def _check_comment(body: dict[str, Any]) -> None:
    if set(body) != _COMMENT_KEYS:
        raise ForbiddenWrite(
            f"a line comment carries exactly {sorted(_COMMENT_KEYS)}, got {sorted(body)}"
        )
    text = body["body"]
    if not isinstance(text, str) or not text.endswith(f"\n\n{DISCLOSURE}"):
        raise ForbiddenWrite("every comment ends with the AI disclosure line")
    if len(text) > MAX_COMMENT_CHARS:
        raise ForbiddenWrite(f"a {len(text)} character comment is not a line comment")
    if body["side"] != "RIGHT" or not isinstance(body["line"], int):
        raise ForbiddenWrite("comments go on a numbered line of the new file, side RIGHT")


def _no_body_check(body: dict[str, Any]) -> None:
    del body


@dataclass(frozen=True, slots=True)
class Route:
    method: str
    pattern: re.Pattern[str]
    why: str
    check: Callable[[dict[str, Any]], None] = _no_body_check


ALLOWED: tuple[Route, ...] = (
    Route(
        "POST",
        re.compile(rf"^/repos/{_NAME}/{_NAME}/dispatches$"),
        "start a review run on our own repository, from the webhook receiver",
    ),
    Route(
        "POST",
        re.compile(rf"^/repos/{_NAME}/{_NAME}/pulls/[1-9][0-9]*/comments$"),
        "leave one line comment on a pull request the App is installed on",
        _check_comment,
    ),
)


def route_for(method: str, url: str) -> Route:
    """The allowed route this write matches, or ForbiddenWrite saying why it has none."""
    method = method.upper()
    if method not in WRITE_METHODS:
        raise ForbiddenWrite(f"{method} is not a write; reads go through GitHubClient")
    parts = urlsplit(url)
    if parts.scheme != "https" or parts.netloc != API_HOST:
        raise ForbiddenWrite(f"{method} {url} is not a request to https://{API_HOST}")
    if parts.query or parts.fragment:
        raise ForbiddenWrite(f"{method} {url} carries a query; no allowed write takes one")
    for route in ALLOWED:
        if route.method == method and route.pattern.match(parts.path):
            return route
    raise ForbiddenWrite(
        f"{method} {parts.path} is not on the write allowlist in pr_lens.github.writes"
    )


async def send(
    client: httpx.AsyncClient,
    method: str,
    url: str,
    *,
    json: dict[str, Any],
    headers: dict[str, str],
) -> httpx.Response:
    route_for(method, url).check(json)
    return await client.request(method, url, json=json, headers=headers)
